### ISSUE TITLE
Not enabling when connecting to a server

### ISSUE THREAD

**Issue by eudaldca** [MySquishyTurtle/MySquishyModTools#2]
When you connect to the lobby it disables, but when you then go to another server it disables :(
(ver. 1.1)

**Comment by MySquishyTurtle** [comment]
Yeah, I noticed this. This is due to the recent patch where I made it detect gamemode changes to turn on and off. I'm going to have to find a loop around - probably having a master toggle for the mod and then a separate toggle for the features.

**Comment by eudaldca** [comment]
You could have it run only when gamemode = 1 or 3

**Comment by MySquishyTurtle** [comment]
Readying to push a fix for it.

**Comment by MySquishyTurtle** [comment]
Patched in c037089336999f21e0f791419fdeb4a9ba7f65b2
