### ISSUE TITLE
Mod doesn't enable when connecting to EU servers

### ISSUE THREAD

**Issue by eudaldca** [MySquishyTurtle/MySquishyModTools#6]
[This](https://github.com/MySquishyTurtle/MySquishyModTools/blob/c037089336999f21e0f791419fdeb4a9ba7f65b2/src/main/java/le/mysquishyturt/mysquishymodtools/connectionHandler/ConnectionHandler.java#L32) should include both US and EU IP's, not only US. Maybe using "*.oc.tc" works?

**Comment by MySquishyTurtle** [comment]
Nah that won't work; however, I should be able to find a way to do it.

**Comment by MySquishyTurtle** [comment]
Thanks, fixed now. <3
